Fix runtime error (missing required argument)
Runtime error:

File "/code/demetsiiify/iiif.py", line 220, in make_manifest
    _fill_manifest_metadata(manifest)
TypeError: _fill_manifest_metadata() missing 1 required positional argument: 'mets_metadata'

Signed-off-by: Stefan Weil <sw@weilnetz.de>